### ISSUE TITLE
Support background colours too

### ISSUE THREAD

**Issue by toothbrush7777777** [spenserblack/ansiform#3]
### Feature
Support for background colours

### Changes
Feature request

**Comment by spenserblack** [comment]
Nice catch! :smiley:

I wonder how the background color options should be "input" :thinking:
`onred` for red background, perhaps?

Also, looks like you've forked this repo. Would you like to be assigned?

**Comment by toothbrush7777777** [comment]
> I wonder how the background color options should be "input" 🤔
> `onred` for red background, perhaps?
> 
> Also, looks like you've forked this repo. Would you like to be assigned?

Yes, maybe `onred` or `on_red`.

You can assign me for this. I might not be able to do it before Monday, though.

**Comment by spenserblack** [comment]
Assigned.

>I might not be able to do it before Monday, though.

No problem. I've neglected to add this feature for two months, so I can certainly wait a little longer :rofl:
