### ISSUE TITLE
Issue with string escape sequences

### ISSUE THREAD

**Issue by toothbrush7777777** [spenserblack/ansiform#4]
### What is the bug?
```rust
ansi!("{;red}\n") == "…{}…\\n"
```

It should not escape existing escape codes.

### Where is the bug?
I tried using `println!(ansi!("\n{;red}\n\n"), 123)` and it wrote the backslash escapes verbatim.

### Expected behavior
It should have printed newlines, not the literal characters.

### What version?
Cargo release v0.1.0

**Comment by spenserblack** [comment]
Another nice catch, thanks!
Looks like `String::parse` can fix this. [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%0Afn%20main()%20%7B%0A%20%20%20%20let%20s%3A%20String%20%3D%20%22%5C%22Hello%5C%22%5C%5C%5Cn%5C%22World%5C%22%22.parse().unwrap()%3B%0A%20%20%20%20println!(%22%7B%7D%22%2C%20s)%3B%0A%7D)

**Comment by spenserblack** [comment]
If anyone would like to make a PR for this bugfix, please include a test 😃

**Comment by toothbrush7777777** [comment]
> Another nice catch, thanks!
> Looks like `String::parse` can fix this. [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%0Afn%20main()%20%7B%0A%20%20%20%20let%20s%3A%20String%20%3D%20%22%5C%22Hello%5C%22%5C%5C%5Cn%5C%22World%5C%22%22.parse().unwrap()%3B%0A%20%20%20%20println!(%22%7B%7D%22%2C%20s)%3B%0A%7D)

No, it does not work ([example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=015574455ba36d611d2b0b590c560c76)).

It looks like we'd need to use `syn` to parse the string.

**Comment by spenserblack** [comment]
Ah, thanks for catching that. Can't believe I added an actual newline (`\\\n`) instead of a properly escaped newline (`\\n`) :facepalm: :laughing:
There are some crates that might be able to help ( like `snailquote::unescape` ), but I agree that `syn` is probably the best solution.

**Comment by toothbrush7777777** [comment]
> 
> 
> Ah, thanks for catching that. Can't believe I added an actual newline (`\\\n`) instead of a properly escaped newline (`\\n`) 🤦 😆
> There are some crates that might be able to help ( like `snailquote::unescape` ), but I agree that `syn` is probably the best solution.

I've got `syn` working in a local copy.
I just need to tidy it up and create a new pull request.

**Comment by spenserblack** [comment]
Thank you for your hard work!
